### ISSUE TITLE
Confusing error when the configured conceptscheme_id is incorrect

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/skosprovider_sqlalchemy#79]
```
2021-11-30 14:19:01,643 ERROR [atramhasis.views.exception_views][waitress-1] No SKOS registry found, please check your application setup
Traceback (most recent call last):
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 108, in _class_requestonly_view
    inst = view(request)
  File "my_thesaurus/.venv/lib/python3.8/site-packages/atramhasis/views/views.py", line 51, in __init__
    raise SkosRegistryNotFoundException()
atramhasis.errors.SkosRegistryNotFoundException: 'No SKOS registry found, please check your application setup'
2021-11-30 14:19:01,652 INFO  [sqlalchemy.engine.Engine][waitress-1] ROLLBACK
2021-11-30 14:19:01,662 INFO  [pyramid_debugtoolbar][waitress-1] Squashed atramhasis.errors.SkosRegistryNotFoundException at http://localhost:6543/
traceback url: http://localhost:6543/_debug_toolbar/313430333536323635363835353336/exception
```

The code does not handle the usecase of an incorrect id
https://github.com/koenedaele/skosprovider_sqlalchemy/blob/2289525ad1cae44ca06beca469b6a5cdb7e4cca2/skosprovider_sqlalchemy/providers.py#L116-L124
So an AttributeError will get raised.

And this is worsened by the fact that the registry swallows these exceptions
https://github.com/koenedaele/skosprovider/blob/b32370a58a57c7f372cb3dcb50d62bc4f43e65be/skosprovider/registry.py#L110-L112

Leaving you no trace of what went wrong.

skosprovider_sqlalchemy should at least log an error. Or raise something else than an AttributeError so it does not get swallowed.

**Comment by koenedaele** [comment]
See koenedaele/skosprovider#102 for improving the skosprovider error handling

**Comment by koenedaele** [comment]
@Wim-De-Clercq Can you send a PR with a possible fix for this issue?

**Comment by koenedaele** [comment]
Skosprovider 1.1.0 now logs an error

**Comment by koenedaele** [comment]
Fixed in skosprovider. Not fixing here.
